name = "OxygenReviseTest"
uuid = "d9097fc9-89cc-4caa-9014-edd044db4ddb"
authors = ["Frankie Robertson <frankie@robertson.name>"]
version = "0.1.0"

[deps]
Oxygen = "df9a0d86-3283-4920-82dc-4555fc0d1d8b"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
